Nearform/migrate to node test
fastify/fastify-env pull request #190
Opened 2024-09-09 06:54 UTC by narendra-reddy-nf

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-09-09 07:33 UTC, mcollina commented on package.json
> +    "c8": "^7.12.0",
latest version of c8 is 10.

2024-09-09 08:27 UTC, Uzlopak commented on test/fastify-env.test.js
> +  // t.plan(2)
?

2024-09-09 08:29 UTC, Uzlopak requested changes
node 20 and 22 have t.plan
https://nodejs.org/api/test.html#contextplancount

2024-09-11 08:21 UTC, simoneb approved these changes

2024-09-11 08:23 UTC, merged